"""add_chat_and_knowledge_tables

Revision ID: de43eb1fd68f
Revises: 001
Create Date: 2026-03-26 00:51:19.308873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de43eb1fd68f'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_chat_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_sessions'))
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('knowledge_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_knowledge_docs_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_docs'))
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('tool_args', sa.Text(), nullable=True),
    sa.Column('tool_result', sa.Text(), nullable=True),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('fk_chat_messages_session_id_chat_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('doc_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['knowledge_docs.id'], name=op.f('fk_doc_chunks_doc_id_knowledge_docs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_doc_chunks'))
    )
    op.create_index(op.f('ix_doc_chunks_doc_id'), 'doc_chunks', ['doc_id'], unique=False)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'warning'::character varying"))
    op.alter_column('alerts', 'is_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_alerts_is_resolved', table_name='alerts')
    op.alter_column('areas', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('areas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('areas_code_key', 'areas', type_='unique')
    op.drop_index('ix_areas_code', table_name='areas')
    op.create_index(op.f('ix_areas_code'), 'areas', ['code'], unique=True)
    op.drop_index('ix_audit_logs_occurred_at_brin', table_name='audit_logs', postgresql_with={'pages_per_range': '64'}, postgresql_using='brin')
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    op.create_unique_constraint(op.f('uq_categories_name'), 'categories', ['name'])
    op.alter_column('import_jobs', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('import_jobs', 'total_rows',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'imported_rows',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'skipped_rows',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'error_rows',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('inventory_events', 'requires_override',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('inventory_events', 'source',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.drop_index('ix_inventory_events_occurred_at_brin', table_name='inventory_events', postgresql_with={'pages_per_range': '32'}, postgresql_using='brin')
    op.create_index(op.f('ix_inventory_events_occurred_at'), 'inventory_events', ['occurred_at'], unique=False)
    op.alter_column('item_barcodes', 'barcode_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'code128'::character varying"))
    op.alter_column('item_barcodes', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('item_barcodes', 'label_printed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('item_barcodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('item_barcodes_barcode_value_key', 'item_barcodes', type_='unique')
    op.create_unique_constraint('uq_item_barcodes_value', 'item_barcodes', ['barcode_value'])
    op.alter_column('items', 'unit',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'pcs'::character varying"))
    op.alter_column('items', 'unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('items', 'sale_price',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('items', 'reorder_level',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('items', 'reorder_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('items', 'lead_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('7'))
    op.alter_column('items', 'is_serialized',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('items_sku_key', 'items', type_='unique')
    op.drop_index('ix_items_name_trgm', table_name='items', postgresql_using='gin')
    op.drop_index('ix_items_sku_trgm', table_name='items', postgresql_using='gin')
    op.drop_index('ix_items_sku', table_name='items')
    op.create_index(op.f('ix_items_sku'), 'items', ['sku'], unique=True)
    op.alter_column('location_barcodes', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('location_barcodes', 'barcode_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'qr'::character varying"))
    op.alter_column('location_barcodes', 'label_printed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('location_barcodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('location_barcodes_barcode_value_key', 'location_barcodes', type_='unique')
    op.drop_index('ix_location_barcodes_barcode_value', table_name='location_barcodes')
    op.create_index(op.f('ix_location_barcodes_barcode_value'), 'location_barcodes', ['barcode_value'], unique=True)
    op.alter_column('locations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('locations_code_key', 'locations', type_='unique')
    op.drop_index('ix_locations_code', table_name='locations')
    op.create_index(op.f('ix_locations_code'), 'locations', ['code'], unique=True)
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'])
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_index(op.f('ix_locations_code'), table_name='locations')
    op.create_index('ix_locations_code', 'locations', ['code'], unique=False)
    op.create_unique_constraint('locations_code_key', 'locations', ['code'])
    op.alter_column('locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('locations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_location_barcodes_barcode_value'), table_name='location_barcodes')
    op.create_index('ix_location_barcodes_barcode_value', 'location_barcodes', ['barcode_value'], unique=False)
    op.create_unique_constraint('location_barcodes_barcode_value_key', 'location_barcodes', ['barcode_value'])
    op.alter_column('location_barcodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('location_barcodes', 'label_printed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('location_barcodes', 'barcode_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'qr'::character varying"))
    op.alter_column('location_barcodes', 'location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_items_sku'), table_name='items')
    op.create_index('ix_items_sku', 'items', ['sku'], unique=False)
    op.create_index('ix_items_sku_trgm', 'items', ['sku'], unique=False, postgresql_using='gin')
    op.create_index('ix_items_name_trgm', 'items', ['name'], unique=False, postgresql_using='gin')
    op.create_unique_constraint('items_sku_key', 'items', ['sku'])
    op.alter_column('items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('items', 'is_serialized',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('items', 'lead_days',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('7'))
    op.alter_column('items', 'reorder_qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('items', 'reorder_level',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('items', 'sale_price',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('items', 'unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('items', 'unit',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'pcs'::character varying"))
    op.drop_constraint('uq_item_barcodes_value', 'item_barcodes', type_='unique')
    op.create_unique_constraint('item_barcodes_barcode_value_key', 'item_barcodes', ['barcode_value'])
    op.alter_column('item_barcodes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('item_barcodes', 'label_printed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('item_barcodes', 'is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('item_barcodes', 'barcode_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'code128'::character varying"))
    op.drop_index(op.f('ix_inventory_events_occurred_at'), table_name='inventory_events')
    op.create_index('ix_inventory_events_occurred_at_brin', 'inventory_events', ['occurred_at'], unique=False, postgresql_with={'pages_per_range': '32'}, postgresql_using='brin')
    op.alter_column('inventory_events', 'source',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('inventory_events', 'requires_override',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('import_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('import_jobs', 'error_rows',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'skipped_rows',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'imported_rows',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'total_rows',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('import_jobs', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint(op.f('uq_categories_name'), 'categories', type_='unique')
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    op.alter_column('categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.create_index('ix_audit_logs_occurred_at_brin', 'audit_logs', ['occurred_at'], unique=False, postgresql_with={'pages_per_range': '64'}, postgresql_using='brin')
    op.drop_index(op.f('ix_areas_code'), table_name='areas')
    op.create_index('ix_areas_code', 'areas', ['code'], unique=False)
    op.create_unique_constraint('areas_code_key', 'areas', ['code'])
    op.alter_column('areas', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('areas', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_index('ix_alerts_is_resolved', 'alerts', ['is_resolved'], unique=False)
    op.alter_column('alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('alerts', 'is_resolved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'warning'::character varying"))
    op.drop_index(op.f('ix_doc_chunks_doc_id'), table_name='doc_chunks')
    op.drop_table('doc_chunks')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('knowledge_docs')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
